--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cooldogedev/libSQL
build-by-default: true
branches:
- main
projects:
  libSQL:
    path: ""
    model: virion
    type: library
    libs:
      - src: cooldogedev/libPromise/libPromise
        version: ^0.0.4
...
